receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp/tempo:
    endpoint: "http://host.docker.internal:4319"
    tls:
      insecure: true
  zipkin:
    endpoint: http://host.docker.internal:9411/api/v2/spans
    format: proto
  otlp/jaeger:
    endpoint: "http://host.docker.internal:4321"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/tempo, zipkin, otlp/jaeger]
